[package]
name = "tui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "minuteman"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
browser = { path = "../browser" }
file_ops = { path = "../file_ops" }
shell_overlay = { path = "../shell_overlay" }
theming = { path = "../theming" }
ratatui = "0.30.2"
crossterm = "0.29.0"
anyhow = "1.0.104"
tokio = { version = "1", features = ["rt-multi-thread", "sync"] }
